SRC += andrewxhc.c andrewxhc_leader.c
INTROSPECTION_KEYMAP_C = $(USER_PATH)/andrewxhc_combos.c

BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
REPEAT_KEY_ENABLE = yes
UNICODE_COMMON = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = no
GRAVE_ESC_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = no
OS_DETECTION_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no
